# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uitemplate/mainwindow.ui'
#
# Created: Tue Dec 09 15:47:55 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(956, 630)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.groupBox_3)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gBListName = QtGui.QGroupBox(self.tab)
        self.gBListName.setObjectName(_fromUtf8("gBListName"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gBListName)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tWTaskList = QtGui.QTableWidget(self.gBListName)
        self.tWTaskList.setObjectName(_fromUtf8("tWTaskList"))
        self.tWTaskList.setColumnCount(5)
        self.tWTaskList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tWTaskList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tWTaskList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tWTaskList.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tWTaskList.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tWTaskList.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_2.addWidget(self.tWTaskList)
        self.verticalLayout_2.addWidget(self.gBListName)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_current = QtGui.QWidget()
        self.tab_current.setObjectName(_fromUtf8("tab_current"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_current)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gBTaskName = QtGui.QGroupBox(self.tab_current)
        self.gBTaskName.setObjectName(_fromUtf8("gBTaskName"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.gBTaskName)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tWComplete = QtGui.QTableWidget(self.gBTaskName)
        self.tWComplete.setObjectName(_fromUtf8("tWComplete"))
        self.tWComplete.setColumnCount(4)
        self.tWComplete.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tWComplete.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tWComplete.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tWComplete.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tWComplete.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tWComplete.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tWComplete.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_7.addWidget(self.tWComplete)
        self.verticalLayout_6.addWidget(self.gBTaskName)
        self.tabWidget.addTab(self.tab_current, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = TaskViewWidget(self.groupBox_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout.addWidget(self.widget)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 956, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_4 = QtGui.QMenu(self.menubar)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.menu_5 = QtGui.QMenu(self.menubar)
        self.menu_5.setObjectName(_fromUtf8("menu_5"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_start_task = QtGui.QAction(MainWindow)
        self.action_start_task.setEnabled(True)
        self.action_start_task.setObjectName(_fromUtf8("action_start_task"))
        self.action_import_task = QtGui.QAction(MainWindow)
        self.action_import_task.setObjectName(_fromUtf8("action_import_task"))
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_accountmanage = QtGui.QAction(MainWindow)
        self.action_accountmanage.setObjectName(_fromUtf8("action_accountmanage"))
        self.action_6 = QtGui.QAction(MainWindow)
        self.action_6.setObjectName(_fromUtf8("action_6"))
        self.action_7 = QtGui.QAction(MainWindow)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.action_9 = QtGui.QAction(MainWindow)
        self.action_9.setObjectName(_fromUtf8("action_9"))
        self.action_10 = QtGui.QAction(MainWindow)
        self.action_10.setObjectName(_fromUtf8("action_10"))
        self.action_task_manage = QtGui.QAction(MainWindow)
        self.action_task_manage.setObjectName(_fromUtf8("action_task_manage"))
        self.action_8 = QtGui.QAction(MainWindow)
        self.action_8.setObjectName(_fromUtf8("action_8"))
        self.action_11 = QtGui.QAction(MainWindow)
        self.action_11.setObjectName(_fromUtf8("action_11"))
        self.action_12 = QtGui.QAction(MainWindow)
        self.action_12.setObjectName(_fromUtf8("action_12"))
        self.action_stop_task = QtGui.QAction(MainWindow)
        self.action_stop_task.setObjectName(_fromUtf8("action_stop_task"))
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_7)
        self.menu_2.addAction(self.action_start_task)
        self.menu_2.addAction(self.action_import_task)
        self.menu_2.addAction(self.action_stop_task)
        self.menu_3.addAction(self.action_4)
        self.menu_4.addAction(self.action_task_manage)
        self.menu_4.addAction(self.action_accountmanage)
        self.menu_4.addAction(self.action_11)
        self.menu_5.addAction(self.action_6)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_task_manage, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.taskManage)
        QtCore.QObject.connect(self.action_accountmanage, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.accountManage)
        QtCore.QObject.connect(self.action_start_task, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.startTask)
        QtCore.QObject.connect(self.tWTaskList, QtCore.SIGNAL(_fromUtf8("cellClicked(int,int)")), MainWindow.twTasklistCellClicked)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("destroyed()")), MainWindow.close)
        QtCore.QObject.connect(self.action_import_task, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.importTask)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "天才吧预约", None))
        self.gBListName.setTitle(_translate("MainWindow", "列表名", None))
        item = self.tWTaskList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "账号", None))
        item = self.tWTaskList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "进度", None))
        item = self.tWTaskList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "代理", None))
        item = self.tWTaskList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "零售店", None))
        item = self.tWTaskList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "服务类型", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "未完成", None))
        self.gBTaskName.setTitle(_translate("MainWindow", "列表名", None))
        item = self.tWComplete.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tWComplete.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tWComplete.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "账号", None))
        item = self.tWComplete.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "零售店", None))
        item = self.tWComplete.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "服务类型", None))
        item = self.tWComplete.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "代理", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_current), _translate("MainWindow", "完成", None))
        self.menu.setTitle(_translate("MainWindow", "文件", None))
        self.menu_2.setTitle(_translate("MainWindow", "任务", None))
        self.menu_3.setTitle(_translate("MainWindow", "设置", None))
        self.menu_4.setTitle(_translate("MainWindow", "管理", None))
        self.menu_5.setTitle(_translate("MainWindow", "帮助", None))
        self.action.setText(_translate("MainWindow", "配置", None))
        self.action_start_task.setText(_translate("MainWindow", "开始任务", None))
        self.action_import_task.setText(_translate("MainWindow", "导入任务", None))
        self.action_4.setText(_translate("MainWindow", "任务列表", None))
        self.action_accountmanage.setText(_translate("MainWindow", "账号管理", None))
        self.action_6.setText(_translate("MainWindow", "关于", None))
        self.action_7.setText(_translate("MainWindow", "登录", None))
        self.action_9.setText(_translate("MainWindow", "更新代理列表", None))
        self.action_10.setText(_translate("MainWindow", "自定义代理", None))
        self.action_task_manage.setText(_translate("MainWindow", "任务管理", None))
        self.action_8.setText(_translate("MainWindow", "计划任务", None))
        self.action_11.setText(_translate("MainWindow", "代理管理", None))
        self.action_12.setText(_translate("MainWindow", "账号管理", None))
        self.action_stop_task.setText(_translate("MainWindow", "停止任务", None))

from taskviewwidget import TaskViewWidget
