# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uitemplate/taskviewwidget.ui'
#
# Created: Wed Dec 10 18:32:58 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(512, 391)
        self.horizontalLayout_7 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.stackedWidget = QtGui.QStackedWidget(Form)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox_11 = QtGui.QGroupBox(self.page)
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 41))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.progressBar = QtGui.QProgressBar(self.groupBox_6)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setAutoFillBackground(True)
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.progressBar.setProperty("value", 1)
        self.progressBar.setTextVisible(True)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_6.addWidget(self.progressBar)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_12.setSizeIncrement(QtCore.QSize(5, 5))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pTSmsChallengeTip = QtGui.QPlainTextEdit(self.groupBox_12)
        self.pTSmsChallengeTip.setMinimumSize(QtCore.QSize(180, 90))
        self.pTSmsChallengeTip.setObjectName(_fromUtf8("pTSmsChallengeTip"))
        self.verticalLayout_2.addWidget(self.pTSmsChallengeTip)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.groupBox_12)
        self.label_6.setMaximumSize(QtCore.QSize(44, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lEPhoneNumber = QtGui.QLineEdit(self.groupBox_12)
        self.lEPhoneNumber.setEnabled(True)
        self.lEPhoneNumber.setObjectName(_fromUtf8("lEPhoneNumber"))
        self.horizontalLayout_3.addWidget(self.lEPhoneNumber)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.groupBox_12)
        self.label_7.setMaximumSize(QtCore.QSize(44, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lESmsCode = QtGui.QLineEdit(self.groupBox_12)
        self.lESmsCode.setEnabled(True)
        self.lESmsCode.setObjectName(_fromUtf8("lESmsCode"))
        self.horizontalLayout_5.addWidget(self.lESmsCode)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addWidget(self.groupBox_12)
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_14.setTitle(_fromUtf8(""))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_14)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_15 = QtGui.QGroupBox(self.groupBox_14)
        self.groupBox_15.setMinimumSize(QtCore.QSize(170, 80))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbVerifyCodePic = QtGui.QLabel(self.groupBox_15)
        self.lbVerifyCodePic.setMaximumSize(QtCore.QSize(161, 78))
        self.lbVerifyCodePic.setText(_fromUtf8(""))
        self.lbVerifyCodePic.setObjectName(_fromUtf8("lbVerifyCodePic"))
        self.horizontalLayout_4.addWidget(self.lbVerifyCodePic)
        self.verticalLayout.addWidget(self.groupBox_15)
        self.groupBox_16 = QtGui.QGroupBox(self.groupBox_14)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.lECaptchaAnswer = QtGui.QLineEdit(self.groupBox_16)
        self.lECaptchaAnswer.setGeometry(QtCore.QRect(11, 24, 133, 20))
        self.lECaptchaAnswer.setObjectName(_fromUtf8("lECaptchaAnswer"))
        self.verticalLayout.addWidget(self.groupBox_16)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pBRefresh = QtGui.QPushButton(self.groupBox_14)
        self.pBRefresh.setMaximumSize(QtCore.QSize(75, 23))
        self.pBRefresh.setObjectName(_fromUtf8("pBRefresh"))
        self.horizontalLayout.addWidget(self.pBRefresh)
        self.pBSumit = QtGui.QPushButton(self.groupBox_14)
        self.pBSumit.setMaximumSize(QtCore.QSize(75, 23))
        self.pBSumit.setObjectName(_fromUtf8("pBSumit"))
        self.horizontalLayout.addWidget(self.pBSumit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addWidget(self.groupBox_14)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.horizontalLayout_8.addWidget(self.groupBox_11)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.page_2)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_7.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.pBSumit, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.submit)
        QtCore.QObject.connect(self.pBRefresh, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.refresh)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox_12.setTitle(_translate("Form", "发送预约码", None))
        self.label_6.setText(_translate("Form", "手机号:", None))
        self.label_7.setText(_translate("Form", "预约码:", None))
        self.groupBox_15.setTitle(_translate("Form", "验证码", None))
        self.groupBox_16.setTitle(_translate("Form", "输入验证码", None))
        self.lECaptchaAnswer.setPlaceholderText(_translate("Form", "输入验证码", None))
        self.pBRefresh.setText(_translate("Form", "刷新", None))
        self.pBSumit.setText(_translate("Form", "确定", None))

