# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uidesigner_res/taskdlg.ui'
#
# Created: Wed Dec 03 18:11:48 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TaskDialog(object):
    def setupUi(self, TaskDialog):
        TaskDialog.setObjectName(_fromUtf8("TaskDialog"))
        TaskDialog.resize(505, 329)
        self.verticalLayout_5 = QtGui.QVBoxLayout(TaskDialog)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tWTask = QtGui.QTabWidget(TaskDialog)
        self.tWTask.setObjectName(_fromUtf8("tWTask"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.gBTaskinfo = QtGui.QGroupBox(self.tab_1)
        self.gBTaskinfo.setMaximumSize(QtCore.QSize(248, 265))
        self.gBTaskinfo.setTitle(_fromUtf8(""))
        self.gBTaskinfo.setObjectName(_fromUtf8("gBTaskinfo"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.gBTaskinfo)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lebelStore = QtGui.QLabel(self.gBTaskinfo)
        self.lebelStore.setObjectName(_fromUtf8("lebelStore"))
        self.horizontalLayout.addWidget(self.lebelStore)
        self.combStore = QtGui.QComboBox(self.gBTaskinfo)
        self.combStore.setEnabled(False)
        self.combStore.setObjectName(_fromUtf8("combStore"))
        self.horizontalLayout.addWidget(self.combStore)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.gBTaskinfo)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.combServType = QtGui.QComboBox(self.gBTaskinfo)
        self.combServType.setEnabled(False)
        self.combServType.setObjectName(_fromUtf8("combServType"))
        self.horizontalLayout_2.addWidget(self.combServType)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.gBTaskinfo)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.lEUserName = QtGui.QLineEdit(self.gBTaskinfo)
        self.lEUserName.setEnabled(False)
        self.lEUserName.setObjectName(_fromUtf8("lEUserName"))
        self.horizontalLayout_3.addWidget(self.lEUserName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.gBTaskinfo)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lEPasswd = QtGui.QLineEdit(self.gBTaskinfo)
        self.lEPasswd.setEnabled(False)
        self.lEPasswd.setEchoMode(QtGui.QLineEdit.Password)
        self.lEPasswd.setObjectName(_fromUtf8("lEPasswd"))
        self.horizontalLayout_4.addWidget(self.lEPasswd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.gBTaskinfo)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lEGovId = QtGui.QLineEdit(self.gBTaskinfo)
        self.lEGovId.setEnabled(False)
        self.lEGovId.setObjectName(_fromUtf8("lEGovId"))
        self.horizontalLayout_5.addWidget(self.lEGovId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.gBTaskinfo)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lEPhoneNumber = QtGui.QLineEdit(self.gBTaskinfo)
        self.lEPhoneNumber.setEnabled(False)
        self.lEPhoneNumber.setObjectName(_fromUtf8("lEPhoneNumber"))
        self.horizontalLayout_6.addWidget(self.lEPhoneNumber)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.gBTaskinfo)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lEReservCode = QtGui.QLineEdit(self.gBTaskinfo)
        self.lEReservCode.setEnabled(False)
        self.lEReservCode.setObjectName(_fromUtf8("lEReservCode"))
        self.horizontalLayout_7.addWidget(self.lEReservCode)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pBStartTask = QtGui.QPushButton(self.gBTaskinfo)
        self.pBStartTask.setEnabled(True)
        self.pBStartTask.setObjectName(_fromUtf8("pBStartTask"))
        self.horizontalLayout_8.addWidget(self.pBStartTask)
        self.pBClear = QtGui.QPushButton(self.gBTaskinfo)
        self.pBClear.setObjectName(_fromUtf8("pBClear"))
        self.horizontalLayout_8.addWidget(self.pBClear)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.horizontalLayout_13.addWidget(self.gBTaskinfo)
        self.gBTaskProcessinfo = QtGui.QGroupBox(self.tab_1)
        self.gBTaskProcessinfo.setMaximumSize(QtCore.QSize(207, 265))
        self.gBTaskProcessinfo.setTitle(_fromUtf8(""))
        self.gBTaskProcessinfo.setObjectName(_fromUtf8("gBTaskProcessinfo"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gBTaskProcessinfo)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.progressBar = QtGui.QProgressBar(self.gBTaskProcessinfo)
        self.progressBar.setMinimumSize(QtCore.QSize(191, 61))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_3.addWidget(self.progressBar)
        self.groupBox = QtGui.QGroupBox(self.gBTaskProcessinfo)
        self.groupBox.setMaximumSize(QtCore.QSize(181, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lbVerifyCodePic = QtGui.QLabel(self.groupBox)
        self.lbVerifyCodePic.setMaximumSize(QtCore.QSize(161, 78))
        self.lbVerifyCodePic.setObjectName(_fromUtf8("lbVerifyCodePic"))
        self.verticalLayout.addWidget(self.lbVerifyCodePic)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_6 = QtGui.QLabel(self.gBTaskProcessinfo)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_10.addWidget(self.label_6)
        self.lEVerfiyCode = QtGui.QLineEdit(self.gBTaskProcessinfo)
        self.lEVerfiyCode.setObjectName(_fromUtf8("lEVerfiyCode"))
        self.horizontalLayout_10.addWidget(self.lEVerfiyCode)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pBOk = QtGui.QPushButton(self.gBTaskProcessinfo)
        self.pBOk.setObjectName(_fromUtf8("pBOk"))
        self.horizontalLayout_9.addWidget(self.pBOk)
        self.pBCancel = QtGui.QPushButton(self.gBTaskProcessinfo)
        self.pBCancel.setObjectName(_fromUtf8("pBCancel"))
        self.horizontalLayout_9.addWidget(self.pBCancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_13.addWidget(self.gBTaskProcessinfo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.tWTask.addTab(self.tab_1, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.tWTask.addTab(self.tab_11, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tWTask)

        self.retranslateUi(TaskDialog)
        self.tWTask.setCurrentIndex(0)
        QtCore.QObject.connect(self.pBStartTask, QtCore.SIGNAL(_fromUtf8("clicked()")), TaskDialog.startTask)
        QtCore.QMetaObject.connectSlotsByName(TaskDialog)
        TaskDialog.setTabOrder(self.combStore, self.lEPasswd)
        TaskDialog.setTabOrder(self.lEPasswd, self.lEPhoneNumber)
        TaskDialog.setTabOrder(self.lEPhoneNumber, self.lEReservCode)
        TaskDialog.setTabOrder(self.lEReservCode, self.pBCancel)
        TaskDialog.setTabOrder(self.pBCancel, self.lEUserName)
        TaskDialog.setTabOrder(self.lEUserName, self.lEGovId)
        TaskDialog.setTabOrder(self.lEGovId, self.pBClear)
        TaskDialog.setTabOrder(self.pBClear, self.pBStartTask)
        TaskDialog.setTabOrder(self.pBStartTask, self.combServType)

    def retranslateUi(self, TaskDialog):
        TaskDialog.setWindowTitle(_translate("TaskDialog", "任务状态", None))
        self.lebelStore.setText(_translate("TaskDialog", "零售店：", None))
        self.label_7.setText(_translate("TaskDialog", "服务类型:", None))
        self.label.setText(_translate("TaskDialog", "用户名：", None))
        self.label_2.setText(_translate("TaskDialog", "密码：", None))
        self.label_3.setText(_translate("TaskDialog", "身份证号：", None))
        self.label_4.setText(_translate("TaskDialog", "手机号：", None))
        self.label_5.setText(_translate("TaskDialog", "预约码：", None))
        self.pBStartTask.setText(_translate("TaskDialog", "开始", None))
        self.pBClear.setText(_translate("TaskDialog", "清空", None))
        self.groupBox.setTitle(_translate("TaskDialog", "单击刷新", None))
        self.lbVerifyCodePic.setText(_translate("TaskDialog", "TextLabel", None))
        self.label_6.setText(_translate("TaskDialog", "验证码：", None))
        self.pBOk.setText(_translate("TaskDialog", "确定", None))
        self.pBCancel.setText(_translate("TaskDialog", "取消", None))
        self.tWTask.setTabText(self.tWTask.indexOf(self.tab_1), _translate("TaskDialog", "任务信息", None))
        self.tWTask.setTabText(self.tWTask.indexOf(self.tab_11), _translate("TaskDialog", "Tab 2", None))

