# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uitemplate/taskviewwidget.ui'
#
# Created: Tue Dec 16 11:01:43 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(430, 277)
        self.horizontalLayout_7 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.stackedWidget = QtGui.QStackedWidget(self.groupBox)
        self.stackedWidget.setMaximumSize(QtCore.QSize(420, 280))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_6 = QtGui.QGroupBox(self.page)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 41))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.progressBar = QtGui.QProgressBar(self.groupBox_6)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setAutoFillBackground(True)
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.progressBar.setProperty("value", 1)
        self.progressBar.setTextVisible(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_8.addWidget(self.progressBar)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pTSmsChallengeTip = QtGui.QPlainTextEdit(self.page)
        self.pTSmsChallengeTip.setMinimumSize(QtCore.QSize(180, 90))
        self.pTSmsChallengeTip.setMaximumSize(QtCore.QSize(180, 159))
        self.pTSmsChallengeTip.setObjectName(_fromUtf8("pTSmsChallengeTip"))
        self.verticalLayout_2.addWidget(self.pTSmsChallengeTip)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setMaximumSize(QtCore.QSize(44, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.lEPhoneNumber = QtGui.QLineEdit(self.page)
        self.lEPhoneNumber.setEnabled(True)
        self.lEPhoneNumber.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lEPhoneNumber.setObjectName(_fromUtf8("lEPhoneNumber"))
        self.horizontalLayout.addWidget(self.lEPhoneNumber)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setMaximumSize(QtCore.QSize(44, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lESmsCode = QtGui.QLineEdit(self.page)
        self.lESmsCode.setEnabled(True)
        self.lESmsCode.setObjectName(_fromUtf8("lESmsCode"))
        self.horizontalLayout_5.addWidget(self.lESmsCode)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_15 = QtGui.QGroupBox(self.page)
        self.groupBox_15.setMinimumSize(QtCore.QSize(180, 80))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_15)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lbVerifyCodePic = QtGui.QLabel(self.groupBox_15)
        self.lbVerifyCodePic.setMinimumSize(QtCore.QSize(160, 70))
        self.lbVerifyCodePic.setText(_fromUtf8(""))
        self.lbVerifyCodePic.setObjectName(_fromUtf8("lbVerifyCodePic"))
        self.verticalLayout.addWidget(self.lbVerifyCodePic)
        self.verticalLayout_3.addWidget(self.groupBox_15)
        self.groupBox_16 = QtGui.QGroupBox(self.page)
        self.groupBox_16.setMaximumSize(QtCore.QSize(153, 53))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_16)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lECaptchaAnswer = QtGui.QLineEdit(self.groupBox_16)
        self.lECaptchaAnswer.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lECaptchaAnswer.setObjectName(_fromUtf8("lECaptchaAnswer"))
        self.horizontalLayout_4.addWidget(self.lECaptchaAnswer)
        self.verticalLayout_3.addWidget(self.groupBox_16)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pBRefresh = QtGui.QPushButton(self.page)
        self.pBRefresh.setMaximumSize(QtCore.QSize(75, 23))
        self.pBRefresh.setObjectName(_fromUtf8("pBRefresh"))
        self.horizontalLayout_3.addWidget(self.pBRefresh)
        self.pBSubmit = QtGui.QPushButton(self.page)
        self.pBSubmit.setMaximumSize(QtCore.QSize(75, 23))
        self.pBSubmit.setObjectName(_fromUtf8("pBSubmit"))
        self.horizontalLayout_3.addWidget(self.pBSubmit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tableWidget = QtGui.QTableWidget(self.page_2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pBOk = QtGui.QPushButton(self.page_2)
        self.pBOk.setObjectName(_fromUtf8("pBOk"))
        self.horizontalLayout_2.addWidget(self.pBOk)
        self.pBCancel = QtGui.QPushButton(self.page_2)
        self.pBCancel.setObjectName(_fromUtf8("pBCancel"))
        self.horizontalLayout_2.addWidget(self.pBCancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.horizontalLayout_7.addWidget(self.groupBox)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pBSubmit, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.submit)
        QtCore.QObject.connect(self.pBRefresh, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.refresh)
        QtCore.QObject.connect(self.tableWidget, QtCore.SIGNAL(_fromUtf8("cellClicked(int,int)")), Form.cellClicked)
        QtCore.QObject.connect(self.tableWidget, QtCore.SIGNAL(_fromUtf8("cellDoubleClicked(int,int)")), Form.cellDoubleClicked)
        QtCore.QObject.connect(self.pBOk, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.accept)
        QtCore.QObject.connect(self.pBCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.rejected)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_6.setText(_translate("Form", "手机号:", None))
        self.label_7.setText(_translate("Form", "预约码:", None))
        self.groupBox_15.setTitle(_translate("Form", "验证码", None))
        self.groupBox_16.setTitle(_translate("Form", "输入验证码", None))
        self.lECaptchaAnswer.setPlaceholderText(_translate("Form", "输入验证码", None))
        self.pBRefresh.setText(_translate("Form", "刷新", None))
        self.pBSubmit.setText(_translate("Form", "确定", None))
        self.pBOk.setText(_translate("Form", "确定", None))
        self.pBCancel.setText(_translate("Form", "取消", None))

