# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uidesigner_res/viewerwidget.ui'
#
# Created: Thu Dec 04 15:27:27 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName(_fromUtf8("Widget"))
        Widget.resize(509, 358)
        self.groupBox_8 = QtGui.QGroupBox(Widget)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 20, 501, 321))
        self.groupBox_8.setMaximumSize(QtCore.QSize(530, 435))
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.tWTask = QtGui.QTabWidget(self.groupBox_8)
        self.tWTask.setDocumentMode(False)
        self.tWTask.setObjectName(_fromUtf8("tWTask"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.progressBar = QtGui.QProgressBar(self.groupBox_5)
        self.progressBar.setMaximumSize(QtCore.QSize(405, 10))
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setAutoFillBackground(True)
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.progressBar.setProperty("value", 1)
        self.progressBar.setTextVisible(True)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_2.setMaximumSize(QtCore.QSize(220, 196))
        self.groupBox_2.setSizeIncrement(QtCore.QSize(5, 5))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pTSmsChallengInfo = QtGui.QPlainTextEdit(self.groupBox_2)
        self.pTSmsChallengInfo.setMinimumSize(QtCore.QSize(200, 90))
        self.pTSmsChallengInfo.setMaximumSize(QtCore.QSize(200, 100))
        self.pTSmsChallengInfo.setObjectName(_fromUtf8("pTSmsChallengInfo"))
        self.verticalLayout_2.addWidget(self.pTSmsChallengInfo)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 70))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lEPhoneNumber = QtGui.QLineEdit(self.groupBox_3)
        self.lEPhoneNumber.setEnabled(False)
        self.lEPhoneNumber.setObjectName(_fromUtf8("lEPhoneNumber"))
        self.horizontalLayout_6.addWidget(self.lEPhoneNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lEReservCode = QtGui.QLineEdit(self.groupBox_3)
        self.lEReservCode.setEnabled(False)
        self.lEReservCode.setMaximumSize(QtCore.QSize(128, 20))
        self.lEReservCode.setObjectName(_fromUtf8("lEReservCode"))
        self.horizontalLayout_7.addWidget(self.lEReservCode)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_9.setTitle(_fromUtf8(""))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox.setMinimumSize(QtCore.QSize(180, 80))
        self.groupBox.setMaximumSize(QtCore.QSize(180, 100))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lbVerifyCodePic = QtGui.QLabel(self.groupBox)
        self.lbVerifyCodePic.setMaximumSize(QtCore.QSize(161, 78))
        self.lbVerifyCodePic.setObjectName(_fromUtf8("lbVerifyCodePic"))
        self.horizontalLayout_3.addWidget(self.lbVerifyCodePic)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lEVerfiyCode = QtGui.QLineEdit(self.groupBox_4)
        self.lEVerfiyCode.setMaximumSize(QtCore.QSize(84, 20))
        self.lEVerfiyCode.setObjectName(_fromUtf8("lEVerfiyCode"))
        self.horizontalLayout.addWidget(self.lEVerfiyCode)
        self.pBOk = QtGui.QPushButton(self.groupBox_4)
        self.pBOk.setObjectName(_fromUtf8("pBOk"))
        self.horizontalLayout.addWidget(self.pBOk)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.horizontalLayout_4.addWidget(self.groupBox_9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.tWTask.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tWTask.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_10.addWidget(self.tWTask)

        self.retranslateUi(Widget)
        self.tWTask.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(_translate("Widget", "Widget", None))
        self.groupBox_2.setTitle(_translate("Widget", "发送预约码", None))
        self.label_4.setText(_translate("Widget", "手机号：", None))
        self.label_5.setText(_translate("Widget", "预约码：", None))
        self.groupBox.setTitle(_translate("Widget", "验证码(双击刷新)", None))
        self.lbVerifyCodePic.setText(_translate("Widget", "TextLabel", None))
        self.groupBox_4.setTitle(_translate("Widget", "输入验证码", None))
        self.pBOk.setText(_translate("Widget", "确定", None))
        self.tWTask.setTabText(self.tWTask.indexOf(self.tab_1), _translate("Widget", "任务信息", None))
        self.tWTask.setTabText(self.tWTask.indexOf(self.tab_2), _translate("Widget", "预订信息", None))

